### PR TITLE
Upgrade to v0.14

### PR DESCRIPTION
**Pull request by AndreMaz**
This PR is an attempt to upgrade Moleculer to v0.14.

At this moment the template is working with a couple of `@ts-ignore` that I would like to fix. However, I don't have enough knowledge about TS so I'm going to need your help  @shawnmcknight @saeedtabrizi 

First thing is the mixin. TS complains about mixin schema not having a name.
image
Any ideas about how to fix this thing? Maybe we can declare mixins property as:
```ts
mixins?: Array<Partial<ServiceSchema>>;
```
What do you think?
___

Second thing is the `MemoryAdapter` that is missing in `moleculer-db` types. @saeedtabrizi can you please help me out on this?
image

___

The third thing is the missing typings for `req` and `res` in `moleculer-web`. `req` and `res` are node.js `http` objects with a couple of Moleculer extensions.  Can you please help me with the typings?

image

___

The last thing is the parameter validation. It complains about shorthand notation introduced in v1 of [`fastest-validator`](https://github.com/icebob/fastest-validator). 
image
Any idea on how to fix it? Maybe add `string` to `ActionParamTypes` ?
https://github.com/moleculerjs/moleculer/blob/78b66743e18f8eb706491b60e156bfb9572035a1/index.d.ts#L49-L65

### CODE REVIEW

**Comment by saeedtabrizi** [comment]
Hi @AndreMaz , ok just i start to implement a true mixins and memory adapter definitions and share it here .

**Comment by icebob** [comment]
Any news about it?

**Comment by AndreMaz** [comment]
I kinda forgot about this PR 😕 
I was working on adding types for `moleculer-web`... I'm going to try to finish them ASAP.
But again, TS is not my _forte_ so a careful review will be necessary.

Still, types for DB adapter are missing. @saeedtabrizi did you had any progress on those?

**Comment by RaphaelSchumacher** [comment]
Any update about this PR ? ;)

**Comment by devalexandre** [comment]
I send a PR
https://github.com/moleculerjs/moleculer-template-project-typescript/pull/23

**Pull request merged**
