### PR TITLE
fix jest

### PR DESCRIPTION
**Pull request by heralight**
fix test execution with jest.

### CODE REVIEW

**Comment by faeron** [comment]
There are some issues with this PR.
First, the additional dependencies on mocha and chai (and their types) are not necessary when using jest and should be removed. It should be sufficient to add jest to `types` in the tsconfig.

The second thing I came across is the conditional include of the jest config files.
The jest config in the `package.json` is only added, if the user answered the question of the `moleculer init` step accordingly. So either add the files only when needed, or let/update the config in package.json where conditional include is already in place.

**Comment by faeron** [comment]
After looking into it, the only needed change may be to add jest to type in tsconfig.json. To prevent the deprecation notice of jest config, just replace `tsConfigFile`with `tsConfig` in the jest part of package.json

**Comment by heralight** [comment]
about mocha (chai too perhaps), you need it to run properly the sample test include in this template. If not, you will have some missing keywords...

**Comment by faeron** [comment]
Just add `jest` to your types in [tsConfig.json](https://github.com/moleculerjs/moleculer-template-project-typescript/blob/master/template/tsconfig.json#L8) and the keywords are not missing.
`{
...
"pretty:"true,
"types": [
       "node",
      "jest"
    ],
 "sourceMap":true,
...}`


The jest typings package`@types/jest` has the keywords (describe,it, etc...) included. Then chai and mocha are not needed anymore.

**Pull request closed without merging**
